jwt:
    secret: ENC[AES256_GCM,data:Ax0ehNMBIX+68UnG,iv:Z/gG3A2jdTc+r62HdunOP9uJsuwPKQumra1g6zT3jII=,tag:EGiO40hgx5GOfKqLy8ORFw==,type:str]
azure:
    connectionString: ENC[AES256_GCM,data:Wcmxbkaze/oVUxaUk2bzgaAkErWzliFAmESDn5Fnq0HuFCitB1RJ/CEJK/u3f/fpQ8PH2xaXoYd6vxdgPmkC5s5nrnxcyWpguORNNw/3p8NuRwBtbqHQgo1COd9yRY/LqchBuQ/OMEURkrsi7movpsTXiTn8mxbM3I4RmVU5nK/DJQKRcv924N5CkvyVAkZQdcofna8PgtwRln6+MGO2R4UCtQONAiDjRf8RruxYW9cq1wh45K/jZzz80c10IPuJJ5TN69amZA6CfH5aXYaz1ZTViDXsAJsVBCsb9oMzsdnATlKRNKpnqaoswDp7Nt6XpWZqwimfbdgCO2QdSRjZ7S689sZKa/N1LtxseIFYVMnICQGejk+G/J7PCOhvGv9CCcrUABJHbE4TfakimeZJCDNzkSqvGP/de7YIcP6/EZLAusLMnUr4f7c1jjDLFvUOcOlTT9LXSp0v2LtHkIvVavhRYCrBxaxymFTIuyfCROTNdZCKsf+Nvn2HEYpsdlZCBBTNvPBktpqGPoSal/LIi/a5WM8hyC1Tb6qElg==,iv:Ie8Me/NJyi9xCP91hk+0Lyr0Zg48tjZqQcMqIYDa4qs=,tag:gB9PejPG/8NNRIOSMAAxbg==,type:str]
    sasToken: ENC[AES256_GCM,data:CK6t3zihzVI5SPcU+F8YasnEzmCjJaCXd23LD1f49iBkZRwmDxl6wWr2gPCkIjEjoMH0+J6XSHtnyF91u7jujKjJ59NOTYSozL8sOB0NhTNtv4eCRpenu8TIt9mqZsSVTAiiaT2nEFNv1CRlVd6dN8BmOuNXC04+MxdYkaKCaxporsg5dkWLCmBgy9SUA9+wjvkO,iv:PO4FiTybFugIJt6UGa0wjSEWLQ87A4y/xMEgs0kkHkU=,tag:EYN94Yn6ZWT0yDEu3XDnFA==,type:str]
    containerName: ENC[AES256_GCM,data:MJP+F5Uk8KfoLhoiQP66+rSuP96pAQ==,iv:u0Y/MK0GH3wM7VLA0mA0o4Ph7tJeIU0jL5J9db+Y11Q=,tag:452QWkPAzf7g9pX5jpnp4w==,type:str]
spring:
    mongodb:
        uri: ENC[AES256_GCM,data:V3aLB4kQ26DA/1f/5P6K4Y30cgoum5H/LOuA3ESvlHv9U6T+w51pZ9EIJoTlnPuu+t0Wpq7XYgA/zzJUxOpl74FeJS2WEwrlYnN96AqBMPlidCkHOfhFPPAdnHRBwrZz0ONuYg==,iv:pgl+in2bRzIGihYnLg0laE+euoRfZEebj6cYc1SZtvI=,tag:is2xJ+JQmLXO6sC8ZlLO8w==,type:str]
    data:
        mongodb:
            auto-index-creation: ENC[AES256_GCM,data:GQxT7Q==,iv:5yysmvDFXecFMEziyplaSrAM3eMQbTqMJ+8Nkha/jA8=,tag:wgfK5FozW/g/c867Nckbjg==,type:bool]
server:
    port: ENC[AES256_GCM,data:1jXN1Q==,iv:JBp3ZGC/gpH0PhtrAcw9pFesVwZHFv07tAFxMIr/XjU=,tag:uT05i1OT83Hv3BT3d6IM0g==,type:int]
web:
    cors:
        allowed-origins:
            - ENC[AES256_GCM,data:jpy56vWglDfkGkDq04X3tcKua3CiIYZtCZcVTvA7SWkakxEs7MfSLYNP,iv:yPd1NDsOTTUdXp+4aZEfoUuG88glAkd0ce/6gE/JCec=,tag:ILKlDKU3ukv5xeTkCbkYow==,type:str]
            - ENC[AES256_GCM,data:0tu/+vhyBVMuPef+9Qn2jyqWFiv79y1hMJoyj2IshaHAfk/GowMExTg=,iv:unawVila/GlMlWsqp3m/WmQxfKw7CzkeaeTREFk+YZI=,tag:ZVnDZajqiBVtI33alvgfpA==,type:str]
            - ENC[AES256_GCM,data:WlE5B9wFJF5IB38/sFX1qzEYl7YxC/Upeu292i8XwQ==,iv:/NU6jwsUm3rN0Yeq0zfdqvnIwXAWNrDjzb5OOGpatV4=,tag:n0A+qVp0qvXzFmdFrBLI8g==,type:str]
        allowed-methods:
            - ENC[AES256_GCM,data:Cylk,iv:y1/1m0XAbH6xzxG2sD6WALO75uX3EhzmPd4EyKxjxRY=,tag:hDjUfVAp1V33To9mBEmP3g==,type:str]
            - ENC[AES256_GCM,data:G/GQ5g==,iv:5plF6akp1MvpaM0itebHWx2fCFrdmmoKLxtpYlKNbWQ=,tag:ZVH3IyUuOC2XM1/BNyIHdA==,type:str]
            - ENC[AES256_GCM,data:20qB,iv:GLT6/jPzfZyZ4PSX84hnnlmlAkXXk8JEuIOdO4erboY=,tag:UbatunrarGKAflIpqrRu2A==,type:str]
            - ENC[AES256_GCM,data:Iw9mC5gS,iv:AqNbsf40yNppeoGnotbdpAVv0j4w6PyUCeRbKiJqYEA=,tag:FiIy0ts5kVJIIxcqUs4cAQ==,type:str]
            - ENC[AES256_GCM,data:WTfHbR+Y9w==,iv:BUGKBQmO2ufYC272xZjgaxXqD+dV0FflotxPKvhB+QY=,tag:5cZmONjbaF13prnepBi4mw==,type:str]
        allowed-headers:
            - ENC[AES256_GCM,data:77DR42N+,iv:LctVS7lNfkOPn7Sh8Jnb/FObdz4FLnnWy/CFnv6TG+I=,tag:eKNPBPWaYGSRRt0O6Rqvbg==,type:str]
            - ENC[AES256_GCM,data:AOKW09o/jKFF95rpXYTYLm3SzaD/gqYiXk+9,iv:GJ7eviygdEq/m5OJhq0NKLxgfVPdP+8SSZ+NG2ad/DI=,tag:kUbJd3kM8eLGLaZJInFu/Q==,type:str]
            - ENC[AES256_GCM,data:AqPS4G4NE+KWNIov,iv:4H09SBQ4BL0YtLXCCT2wnn6y+efUqd0LJS4t+htXlZE=,tag:4Bga0Z4/z925gI2GEpnUOA==,type:str]
            - ENC[AES256_GCM,data:HMqvSr/z,iv:e8qBPmrB470l33MJcpyFz74WWxrCCeVYxTXMWZscQ4s=,tag:AEI87G6vbX3s2YKcqqFNaA==,type:str]
            - ENC[AES256_GCM,data:cu+1WBycZApN,iv:7kCSjP2qxBQOSk1fZYtKcf8TkK//Plp/0GkuLZY/gmY=,tag:7lsW5Ps+GoHy9usc99YF+Q==,type:str]
            - ENC[AES256_GCM,data:nUGhOIThxd/tsLnIog==,iv:fc6VFtr0NT/uNxTbuWNOSLRBasyKF5b4VMA/2PuZeVo=,tag:EqLmcY/NPI4k6AWMQ6ER7A==,type:str]
            - ENC[AES256_GCM,data:seXIGttL,iv:STLqVbINrZVg9/g58GbzF5VV1lcSHSRowLD3/rfbbJI=,tag:6Z+sJqLkq/WSWUPNSXdB/g==,type:str]
            - ENC[AES256_GCM,data:UbQFlT9MM5IphWw8NupUGQ==,iv:0pveNQNX6jkX12IaTMUuhRLwE+EXNg1Alumfiebb+XQ=,tag:6TILlqHnw6w6RuU2oBKduA==,type:str]
            - ENC[AES256_GCM,data:ypY+NyBFU0UIMJ2glNasKrrvrsVvqSynk93hWsE=,iv:SZKPHQCFLH7oES/stM1x3u20IZD0nKajLJZDnkEzxqI=,tag:HLbCxbD2rbUQ31QiVRzl/Q==,type:str]
            - ENC[AES256_GCM,data:2znW9P5/ReUkxRT4Ta82iz6lOdJ7r2mPYXFVvKAq,iv:RVGD5882YXCiOHjVpYxM7DS91zFVHJ8aPZ74nv7UcCM=,tag:YQszLXMiC4DJbCjmswjq7Q==,type:str]
        expose-headers:
            - ENC[AES256_GCM,data:gKOafgLV,iv:M2bzWuoUxlFNj3E+adXyB/lyWtnoW+GqAcxBq8PSdkI=,tag:5rSFdJBquB3YOjYnNBpQ9w==,type:str]
            - ENC[AES256_GCM,data:E7NI0OY8KawR4CcI,iv:YMIg75Q8SDy2hy4FBDqcV+OBQcVcFRK7L+Pz4S9fYoY=,tag:XfRbTuATx9k7zCpPZzk41g==,type:str]
            - ENC[AES256_GCM,data:+cZOjI+F,iv:2ENK2wxOP/0ZP0U9z7oxo811y6TIFu9W93XzgbPt1zA=,tag:dcyjEsBK2qzSMgsMaUXLZw==,type:str]
            - ENC[AES256_GCM,data:0EHVIFJlylkd,iv:h9waw71y4cmn1dpivaL9uvyUzpdS69NeJmSWfbKgDaU=,tag:vjey1Kp2tLFXLHR/M0WHcA==,type:str]
            - ENC[AES256_GCM,data:83ahchsisLuLT/t09g==,iv:HI4ffFkcag6ianSBJdWec4I4UoDGGn45iuzXY78YivA=,tag:VINI8aYBJ1mjc1dE7gQ+Jg==,type:str]
            - ENC[AES256_GCM,data:yIRff72v3anqwKbcq6X7ftxvc9wuC0cuyLoZ,iv:qIE8jSuTKobS6S0iW8Oi5d3me7GmcfmHMTDRt7CdS84=,tag:bjZQZgNcEM9wKax6Ax7TtA==,type:str]
            - ENC[AES256_GCM,data:KXUOvRmfXZbVBTbsryOWktccvU5mcsRquudhvLfPXp4=,iv:9jVQkHesBrkTCAKSm7LjSA7Ir3f2XBpg4Fl1ScUrEuI=,tag:DupPU5ghsE9DxSbP6GkZfQ==,type:str]
        allow-credentials: ENC[AES256_GCM,data:gsCxvg==,iv:9FB8wOxijOvqOstkwFh/c2EGumU2BLQjjHr6yl3LcZA=,tag:XsDdB6IZB356Xv6fdleiqg==,type:bool]
sops:
    age:
        - recipient: age14rfhef89myvcwtngnep3tuc2hq0cukgkgn3w98teaa8sqhttd9pqslq2gr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZXlSczg0cnF1d29WdlpU
            RDFMeG4vLzVkbmdXaGlmc2VEZXRMYjhrcXh3ClU4c2lkOUxGdE5hajRRaWExbnBN
            NFJiOWxMeDZ5RUdROWp2OUdNcDdpMWsKLS0tIGhkVGI5bTFLUWdFUDFERlR1Mi83
            eWNkZktySWZWVEg2VXpiR0ZWVEhEakUKfnUnlx+UjfZnwowdy2rwlFgt66MglsLL
            FYeKzLX/dP6rV2tCx79qzMSHkjX0ZDYSGvDmLuaz6YwWnIZdKSnEaQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dh8a2ar5vtue8upyxdk9n47uqqpgmkrnst0cr623qszqm9tptv5sx9026c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0L1RTQW0zOVQ2akt3TUNi
            YnVJVCs5akVFRElHb01PWkNsdkpqSnJ6V1RRCkN4N0JqeERiMkRjOXpEVWhHeThv
            VW5Md1FYeXM0ODA0WEtZMnRjdmxzZTAKLS0tIHFxUFFOeEprUXZwa3dpN3U4dVFM
            RFd0NUtHaVJPWkFoMlJRVjBUQlJRVE0KW/cY0G3oHnnuhXd3v5o5HmgaxoC+bH+r
            cBbpli8hiXwAsL20YJWX9LWvGJReEuAX5ReFmc2z0kjBE/oKQd6kGw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cq6xtpmyzsum0fc2uk2dwda6rksp6dd8v2m654ev604d4n65cu8synu99s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1M0wyNThZb3NoOUNNamhp
            VkU5UmhaWG5jVHF4TURoWTNTZm1KbzNiUXlzCldkSTYramdIMXl4WmZEMXh5bmly
            TjhuQ0QrWENCcG9QWlJ3aGg3UXBiRU0KLS0tIDNQc1M0ejJHdTNURG10RzJtQWlm
            bWRzdU9xWWpRSVF4Q2dGMkQ4d3NnbzgKI5LNzuTJTpKbgddsRaIRuHN70LhCJfdR
            mN9VZTdes7Wv6+2p9Cf/rWs1x5ugpDxrk4QVsPh7xi7wJzP3U1qcjw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zfr86gs33mx2lfpc0083lweet3za5ufu0wsfqch4fe2glpdqqdsq0mjp6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SlN5VFBucWdBbFhTZXFu
            UU9EWStrVUJPbzBBTElEdE1BQzF3LytCMkNRCnpjOHk3SEFaaHNMMk1aVDlYSzEz
            Z0dZdDlCcFhGSWlmZ1dlZ3lRM1ZDUUUKLS0tIENFdnBCalN3YnpMbUhGT0Jzckp3
            eW1xNGs0elhaSDlqL1ZYZlRJNWIzYXMKDvq76xuFaesxQa1YN8WBNofrYPr0jG14
            XxVx/Wh/x9SbCEdIG2FdYHRhFa8djxnbSQJqB0pKQJCXBA/5XKoyqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pg2reqfck7et78amrcvvzlp7zjm5hy8vg8em70mqv5ww5ark6f5s5xvpvp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUHViQVVEN1llcmprNnVv
            bVQxYVZrbS81RFJGcENDT2lmTnlMLy9jckNVCmtmb3Ayc3FJekRvMFRtRWo4eGpq
            NUNvQThGZ0FDZG9WSUxZWHdWMzdxbHMKLS0tIFljZ1Z0Q1VhdkozQVNBdCt6aXZC
            bmZpOERNTy9hU0UwOXZyV0tKUnI5VVUKw3yLotALSOVcWc32T1Etq/DbHmnj5ezB
            b8Z9sBwFfZapRkpuT8Rzs536HAPBWnQVAL1vb+/Em/0qua033uNpDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T04:13:58Z"
    mac: ENC[AES256_GCM,data:drc1mwOWWZiakFzysOFl9xbw2OMRM1B6aR4edY+k0ybRxG+FdLAyzrlWjsN8Vh3bHeaEss7I7l0yhksBAG9+mA2jP7/JijIulb5C8Yvuh2MNnDtsMxZH/aaBloTo+BJor/1lVNrcaep+hmkKYMOParu6FQChrBTKps1nl6dpJrI=,iv:P15VkX6VR48RPwfXTK56qzdxbP8FpFXtWudNSp/XJWw=,tag:HjTTy/G5FEzyqGQGISFoPg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
