name: build_deploy_azure_container_app
env:
  JAVA_VERSION: '21'                  # set this to the Java version to use
  DISTRIBUTION: 'temurin'             # set this to the Java distribution

on:
  push:
    branches:
      - 'main'
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "pom.xml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v4

      - name: Setup SOPS
        uses: nhedger/setup-sops@v2
        with:
          version: 3.7.3

      - name: Setup age
        uses: alessiodionisi/setup-age-action@v1.3.0

      - name: Run SOPS
        env:
          SOPS_AGE_KEY: ${{ secrets.AGE_SECRET_KEY }}
        run: sops -d src/main/resources/application.enc.yml > src/main/resources/application.yml

      - name: Set up Java version
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: 'maven'

      - name: Build OCI image with Maven
        run: mvn spring-boot:build-image

      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Tag and push image'
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.registry }}.azurecr.io
          username: ${{ secrets.service_principal }}
          password: ${{ secrets.service_principal_password }}
      - run: |
          docker tag chemlab:0.0.1-SNAPSHOT ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}:${{ github.sha }}
          docker push ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}:${{ github.sha }}

      - name: 'Purge old images from ACR'
        run: |
          az acr run --registry ${{ secrets.registry }} --cmd "acr purge --filter '*:.*' --ago 0d --keep 10 --untagged" /dev/null

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: ${{ secrets.registry }}
          containerAppName: chemlab
          resourceGroup: college-projects
          imageToDeploy: ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}:${{ github.sha }}
